ALTER SESSION SET NLS_DATE_FORMAT ='yyyy-mm-dd';/
ALTER SESSION SET NLS_TIMESTAMP_FORMAT ='hh:mi:ss';/

CREATE TABLE SERVICE ( 
Emp_ID INT NOT NULL,
Guest_Ssn INT NOT NULL,
RoomNo INT NOT NULL,
ServType VARCHAR(30),
ServCost INT,
Serv_Date DATE DEFAULT CURRENT_DATE,
Serv_Time TIMESTAMP,
PRIMARY KEY (Emp_ID, Guest_Ssn, RoomNo),
FOREIGN KEY (Emp_ID) REFERENCES EMPLOYEE(EmployeeID),
FOREIGN KEY (Guest_Ssn) REFERENCES GUEST(Ssn),
FOREIGN KEY (RoomNo) REFERENCES ROOM(RoomNo));/

INSERT INTO SERVICE(Emp_ID,Guest_Ssn ,RoomNo, ServType, ServCost, Serv_Time)
VALUES(565, 123456789 ,218, 'luggage delivery', 0, '05:20:23');/

SELECT * FROM SERVICE;/